### ISSUE TITLE
Sample app not working

### ISSUE THREAD

**Issue by luebken** [aspnet/aspnet-docker#67]
I've tried to get the example running from this guide http://blogs.msdn.com/b/webdev/archive/2015/01/14/running-asp-net-5-applications-in-linux-containers-with-docker.aspx

Application code: https://github.com/aspnet/Home/tree/master/samples/HelloWeb
Full code can be found here: https://github.com/luebken/asp-docker

And get the error:
``` 
But I get the error: ○ → docker run -P asp-docker
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
Kestrel 1.0.0-beta3
Microsoft.AspNet.Diagnostics 1.0.0-beta3
Microsoft.AspNet.Hosting 1.0.0-beta3
Microsoft.AspNet.Server.WebListener 1.0.0-beta3
Microsoft.AspNet.StaticFiles 1.0.0-beta3

Searched Locations:
/{name}/project.json
/root/.dnx/packages/{name}/{version}/{name}.nuspec
/usr/lib/mono/4.5/{name}.dll
/usr/lib/mono/4.5/Facades/{name}.dll
```

**Comment by tlk** [comment]
Go for the dev branch rather than master. Also, see aspnet/Home#537 (shameless plug).

**Comment by luebken** [comment]
That worked thanks.

Unfortunately when I start my containers on the host I can't specify `-it`. And as far as I can see this a required workaround currently. Right?

**Comment by ahmetalpbalkan** [comment]
You can just do -dt , -t is the one creating the pseudo-tty stream.

**Comment by luebken** [comment]
The problem is on the host I can't specify any run options.

**Comment by ahmetalpbalkan** [comment]
Umm why? Are you getting errors?

**Comment by mdevilliers** [comment]
I'm facing the same issue as @ahmetalpbalkan 

We are trying to run in kubernentes and you can't specify a the -t argument.

I believe the underlying problem in aspnet/Hosting has been fixed but I'm having trouble restoring the nuget packages 

```
FROM microsoft/aspnet

COPY project.json /app/

WORKDIR /app

RUN ["dnu", "restore", "-s", "https://www.myget.org/F/aspnetvnext/api/v2" , "-f", "https://nuget.org/api/v2"]

COPY . /app

EXPOSE 5004

ENTRYPOINT ["dnx", "project.json", "kestrel"]
```

leads to an error

```
markdv@ubuntu:~/Desktop/kubernetes-bestiary/aspvnext/web-image$ docker run -p 80:5004 mdevilliers/aspvnext-image
System.InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' has been registered.
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService (IServiceProvider provider, System.Type serviceType) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[IApplicationEnvironment] (IServiceProvider provider) [0x00000] in <filename unknown>:0 
  at Microsoft.AspNet.Hosting.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 

```

I'm up for making this a new issue if you think I've hijacked this one?


Mark

**Comment by ahmetalpbalkan** [comment]
@mdevilliers can you please open a separate issue for that one? I think you would need a beta5 image to get the fix (but I'm not sure if the fix made it to beta5), and we don't have beta5 image yet.

The alternative workaround to `-t` is to have `ENTRYPOINT sleep 9999999999 | dnx ....` for now, unfortunately.

**Comment by mdevilliers** [comment]
Will do,

Thanks

Mark

**Comment by ahmetalpbalkan** [comment]
@luebken is this resolved?

**Comment by luebken** [comment]
Unfortunalty not. 

I tried 1.0.0-beta5 by:
* patching [project.json](https://github.com/luebken/asp-docker/blob/master/project.json) to use "1.0.0-beta5" dependencies 
* and using `FROM microsoft/aspnet:1.0.0-beta5
` in the [Dockerfile](https://github.com/luebken/asp-docker/blob/master/Dockerfile)

Still getting the error:
```
± |master ✗| → docker run -P asp-docker
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   Kestrel 1.0.0-beta5
   Microsoft.AspNet.Diagnostics 1.0.0-beta5
   Microsoft.AspNet.Hosting 1.0.0-beta5
   Microsoft.AspNet.Server.WebListener 1.0.0-beta5
   Microsoft.AspNet.StaticFiles 1.0.0-beta5

Searched Locations:
  /{name}/project.json
  /root/.dnx/packages/{name}/{version}/{name}.nuspec
  /usr/lib/mono/4.5/{name}.dll
  /usr/lib/mono/4.5/Facades/{name}.dll

Try running 'dnu restore'.

  at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) [0x00000] in <filename unknown>:0
  at dnx.host.Bootstrapper.RunAsync (System.Collections.Generic.List`1 args, IRuntimeEnvironment env) [0x00000] in <filename unknown>:0
```

**Comment by ahmetalpbalkan** [comment]
@luebken so the HelloWeb/HelloMvc applications here: https://github.com/aspnet/Home/tree/v1.0.0-beta5/samples/1.0.0-beta5 works when the following Dockerfile added to the project root:

```
FROM microsoft/aspnet:1.0.0-beta5
COPY . /app
WORKDIR /app
RUN dnu restore
ENTRYPOINT sleep 10000 | dnx . kestrel
```

image is built and executed like `docker run -t -d -P [image]`, that is what's verified in our CI currently. Can you please try that and see if those work correctly in your set up, if so, maybe you can reverse engineer from what's working to what's not working.

**Comment by luebken** [comment]
@ahmetalpbalkan I can confirm that your setup is working for me.

I guess I have some problems my `project.json` which I need to trace down. 

This leaves this thread with two questions:

* Where can we check in the Dockerfile to continuously test this manner? 
* Where do we track the issue of the necessity to specify `-t`for the pseudo-tty stream?

**Comment by ahmetalpbalkan** [comment]
@luebken That's great to hear.

For the CI of the images, we do test them, however adding Dockerfiles to the aspnet/Home/samples and testing them with Docker does not seem necessary. 

Looks like the “server exit upon key press” issue is merged a long time ago. https://github.com/aspnet/Hosting/pull/255 However I don't know if this fix has made it to 1.0.0-beta5. Are you still seeing the “server dying after a few minutes” if you run beta5 without `-t`?

**Comment by luebken** [comment]
For me a Dockerfile would be convenient to test and point to. But I can also maintain a fork for now. 




The problem with -t is that I can't specify it. I don't have the means to change docker run flags.

**Comment by ahmetalpbalkan** [comment]
I see. So you don't specify -t to a beta5 app and it still dies after a while?




—Alp
http://alp.im

**Comment by jcorioland** [comment]
Hi,

I am trying to run the 1.0.0-beta5 samples with the docker file propsed by @ahmetalpbalkan but I have a lot of task cancelled when running the dnu restore command :

![image](https://cloud.githubusercontent.com/assets/4435138/8541455/a60a0b5a-248e-11e5-9dfc-5edec78c29e1.png)

Does anyone get the same behavior ?
I have the same with other apps / docker files that were working before this version. 

Thanks,

Julien

**Comment by yngndrw** [comment]
I have also noticed this on one of my samples, but not on the other.

This fails:
https://github.com/yngndrw/ASPNetTest

This succeeds:
https://github.com/yngndrw/ASPNetHelloWeb
http://aspnethelloweb.cloud.hostilezone.net/

I'm using Dokku and the aspnethelloweb sample is configured with Docker caching and caching of the NuGet packages, although the caching doesn't work yet and I haven't had the time to look into either this restoration issue or the caching issue. (I'm sure the caching issue is just configuration, but maybe it is working and that is why this sample is working ?)

Like I say I haven't had the time to look at them in much detail but hopefully this helps narrow things down a little.

**Comment by ahmetalpbalkan** [comment]
@jcorioland @yngndrw this looks like a separate issue and likely it's not just Docker... If you have a Linux/Mac, please run these outside Docker containers and report issues to the correct github.com/aspnet/ repos.

**Comment by yngndrw** [comment]
I just tried it again both on a local Ubuntu VM and in Dokku and found that it worked in both places. The downloads seem really slow from the Dokku version despite it running on a real server so maybe it was just poor outward connectivity - I have been having some internet stability issues with the server recently.

@jcorioland I'd suggest that you verify that your connectivity is good before continuing.

**Comment by ahmetalpbalkan** [comment]
Closing as it's not relevant to the docker image directly.
